In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn import metrics

# First attempt at model selection without data on client job positions

In [2]:
df = pd.read_csv('bank_data_without_jobs.csv',
                index_col='ID')
df

CR_PROD_CNT_IL  AMOUNT_RUB_CLO_PRC  TURNOVER_DYNAMIC_IL_1M  \
ID                                                                   
146841       -0.243932           -0.380232               -0.044824   
146842       -0.243932            0.016835               -0.044824   
146843       -0.243932           -0.313313               -0.044824   
146844       -0.243932           -0.380232               -0.044824   
146845       -0.243932           -0.380232               -0.044824   
...                ...                 ...                     ...   
590822       -0.243932           -0.380232               -0.044824   
590823       -0.243932           -0.380232               -0.044824   
590825       -0.243932            0.019401               -0.044824   
590826       -0.243932           -0.380232               -0.044824   
590828       -0.243932           -0.380232               -0.044824   

        AMOUNT_RUB_SUP_PRC  REST_DYNAMIC_FDEP_1M  REST_DYNAMIC_SAVE_3M  \
ID                                                                       
146841           -0.582347              -0.05133              2.356500   
146842            1.221828              -0.05133             -0.312371   
146843           -0.582347              -0.05133             -0.312371   
146844           -0.582347              -0.05133             -0.283428   
146845           -0.582347              -0.05133             -0.312371   
...                    ...                   ...                   ...   
590822           -0.582347              -0.05133             -0.312371   
590823           -0.582347              -0.05133             -0.312371   
590825            0.119528              -0.05133             -0.312371   
590826           -0.582347              -0.05133             -0.312371   
590828           -0.582347              -0.05133             -0.294876   

        CR_PROD_CNT_VCU  REST_AVG_CUR  AMOUNT_RUB_NAS_PRC  \
ID                                                          
146841        -0.169589      0.477531           -0.248485   
146842        -0.169589     -0.330458           -0.248485   
146843        -0.169589      0.247411           -0.248485   
146844        -0.169589     -0.124857           -0.248485   
146845        -0.169589      0.029532           -0.248485   
...                 ...           ...                 ...   
590822        -0.169589     -0.301613           -0.248485   
590823        -0.169589      1.927086            2.804227   
590825        -0.169589      0.843853            0.113815   
590826        -0.169589     -0.288932            3.034981   
590828        -0.169589     -0.292957           -0.248485   

        TRANS_COUNT_SUP_PRC  ...  PACK_103  PACK_104  PACK_105  PACK_107  \
ID                           ...                                           
146841            -1.004598  ...         0         0         0         0   
146842             1.446347  ...         0         0         0         0   
146843            -1.004598  ...         0         0         0         0   
146844            -1.004598  ...         0         0         0         0   
146845            -1.004598  ...         0         0         0         0   
...                     ...  ...       ...       ...       ...       ...   
590822            -1.004598  ...         0         1         0         0   
590823            -1.004598  ...         0         1         0         0   
590825             0.135764  ...         0         0         0         0   
590826            -1.004598  ...         0         0         0         0   
590828            -1.004598  ...         0         0         0         0   

        PACK_108  PACK_109  PACK_301  PACK_k01  PACK_m01  PACK_o01  
ID                                                                  
146841         0         0         0         1         0         0  
146842         0         0         0         0         0         0  
146843         0         0         0         0         0         0  
146844

In [4]:
df.TARGET.value_counts(normalize=True)

0    0.918565
1    0.081435
Name: TARGET, dtype: float64

Classes are imbalanced. It is important to identify items from class 1.

In [3]:
X = df.drop(columns = 'TARGET'); X

CR_PROD_CNT_IL  AMOUNT_RUB_CLO_PRC  TURNOVER_DYNAMIC_IL_1M  \
ID                                                                   
146841       -0.243932           -0.380232               -0.044824   
146842       -0.243932            0.016835               -0.044824   
146843       -0.243932           -0.313313               -0.044824   
146844       -0.243932           -0.380232               -0.044824   
146845       -0.243932           -0.380232               -0.044824   
...                ...                 ...                     ...   
590822       -0.243932           -0.380232               -0.044824   
590823       -0.243932           -0.380232               -0.044824   
590825       -0.243932            0.019401               -0.044824   
590826       -0.243932           -0.380232               -0.044824   
590828       -0.243932           -0.380232               -0.044824   

        AMOUNT_RUB_SUP_PRC  REST_DYNAMIC_FDEP_1M  REST_DYNAMIC_SAVE_3M  \
ID                                                                       
146841           -0.582347              -0.05133              2.356500   
146842            1.221828              -0.05133             -0.312371   
146843           -0.582347              -0.05133             -0.312371   
146844           -0.582347              -0.05133             -0.283428   
146845           -0.582347              -0.05133             -0.312371   
...                    ...                   ...                   ...   
590822           -0.582347              -0.05133             -0.312371   
590823           -0.582347              -0.05133             -0.312371   
590825            0.119528              -0.05133             -0.312371   
590826           -0.582347              -0.05133             -0.312371   
590828           -0.582347              -0.05133             -0.294876   

        CR_PROD_CNT_VCU  REST_AVG_CUR  AMOUNT_RUB_NAS_PRC  \
ID                                                          
146841        -0.169589      0.477531           -0.248485   
146842        -0.169589     -0.330458           -0.248485   
146843        -0.169589      0.247411           -0.248485   
146844        -0.169589     -0.124857           -0.248485   
146845        -0.169589      0.029532           -0.248485   
...                 ...           ...                 ...   
590822        -0.169589     -0.301613           -0.248485   
590823        -0.169589      1.927086            2.804227   
590825        -0.169589      0.843853            0.113815   
590826        -0.169589     -0.288932            3.034981   
590828        -0.169589     -0.292957           -0.248485   

        TRANS_COUNT_SUP_PRC  ...  PACK_103  PACK_104  PACK_105  PACK_107  \
ID                           ...                                           
146841            -1.004598  ...         0         0         0         0   
146842             1.446347  ...         0         0         0         0   
146843            -1.004598  ...         0         0         0         0   
146844            -1.004598  ...         0         0         0         0   
146845            -1.004598  ...         0         0         0         0   
...                     ...  ...       ...       ...       ...       ...   
590822            -1.004598  ...         0         1         0         0   
590823            -1.004598  ...         0         1         0         0   
590825             0.135764  ...         0         0         0         0   
590826            -1.004598  ...         0         0         0         0   
590828            -1.004598  ...         0         0         0         0   

        PACK_108  PACK_109  PACK_301  PACK_k01  PACK_m01  PACK_o01  
ID                                                                  
146841         0         0         0         1         0         0  
146842         0         0         0         0         0         0  
146843         0         0         0         0         0         0  
146844

In [4]:
y = df.TARGET

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.33,
                                                    random_state=8,
                                                   shuffle=True,
                                                   stratify=y)

In [7]:
from sklearn.ensemble import RandomForestClassifier

In [30]:
params = {'n_estimators':[200, 300, 400], 
          'max_depth': [10, 50, None],
         'max_samples': [20000, None]}

In [31]:
%%time
estimator = RandomForestClassifier(criterion='gini', 
                                   max_features='sqrt', 
                                   bootstrap=True, 
                                   oob_score=False, 
                                   n_jobs=-1,
                                   random_state=8, 
                                   class_weight='balanced_subsample')
forest_clf = GridSearchCV(estimator=estimator,
                          param_grid=params,
                          scoring='balanced_accuracy', 
                          n_jobs=-1,
                          refit=True,
                          cv=2).fit(X_train, y_train)

CPU times: total: 5min 21s
Wall time: 17min 53s


In [32]:
forest_clf.best_score_

0.7232999328766789

In [33]:
forest_clf.best_params_

{'max_depth': 10, 'max_samples': None, 'n_estimators': 400}

In [34]:
params = {'n_estimators':[350, 400, 500, 600], 
          'max_depth': [5, 10, 20],
         'max_samples': [None]}

In [35]:
%%time
estimator = RandomForestClassifier(criterion='gini', 
                                   max_features='sqrt', 
                                   bootstrap=True, 
                                   oob_score=False, 
                                   n_jobs=-1,
                                   random_state=8, 
                                   class_weight='balanced_subsample')
forest_clf = GridSearchCV(estimator=estimator,
                          param_grid=params,
                          scoring='balanced_accuracy', 
                          n_jobs=-1,
                          refit=True,
                          cv=2).fit(X_train, y_train)

CPU times: total: 7min 59s
Wall time: 18min 48s


In [36]:
forest_clf.best_score_

0.7236654347950653

In [37]:
forest_clf.best_params_

{'max_depth': 10, 'max_samples': None, 'n_estimators': 600}

In [38]:
best_forest_clf = forest_clf.best_estimator_

In [39]:
y_pred = best_forest_clf.predict(X_test)

In [40]:
metrics.accuracy_score(y_test, y_pred)

0.724586863231894

In [41]:
metrics.balanced_accuracy_score(y_test, y_pred)

0.7291611892585697

In [42]:
metrics.recall_score(y_test, y_pred)

0.7346254583551598

In [43]:
y_pred_proba = best_forest_clf.predict_proba(X_test); y_pred_proba

array([[0.57891012, 0.42108988],
       [0.82172376, 0.17827624],
       [0.64296721, 0.35703279],
       ...,
       [0.73035572, 0.26964428],
       [0.36085865, 0.63914135],
       [0.73782369, 0.26217631]])

In [44]:
metrics.roc_auc_score(y_test, y_pred_proba[:, 1])

0.8024670108544097

In [45]:
metrics.confusion_matrix(y_test, y_pred)

array([[77919, 29749],
       [ 2533,  7012]], dtype=int64)

In [48]:
metrics.confusion_matrix(y_test, y_pred, normalize='true')

array([[0.72369692, 0.27630308],
       [0.26537454, 0.73462546]])

Further adjustments can be made by changing the threshold depending on business requirements

# First attempt at model selection with data on client job positions

In [2]:
df = pd.read_csv('bank_data_with_jobs.csv',
                index_col='ID')
df

CR_PROD_CNT_IL  AMOUNT_RUB_CLO_PRC  TURNOVER_DYNAMIC_IL_1M  \
ID                                                                   
146841       -0.243932           -0.380232               -0.044824   
146842       -0.243932            0.016835               -0.044824   
146843       -0.243932           -0.313313               -0.044824   
146844       -0.243932           -0.380232               -0.044824   
146845       -0.243932           -0.380232               -0.044824   
...                ...                 ...                     ...   
590822       -0.243932           -0.380232               -0.044824   
590823       -0.243932           -0.380232               -0.044824   
590825       -0.243932            0.019401               -0.044824   
590826       -0.243932           -0.380232               -0.044824   
590828       -0.243932           -0.380232               -0.044824   

        AMOUNT_RUB_SUP_PRC  REST_DYNAMIC_FDEP_1M  REST_DYNAMIC_SAVE_3M  \
ID                                                                       
146841           -0.582347              -0.05133              2.356500   
146842            1.221828              -0.05133             -0.312371   
146843           -0.582347              -0.05133             -0.312371   
146844           -0.582347              -0.05133             -0.283428   
146845           -0.582347              -0.05133             -0.312371   
...                    ...                   ...                   ...   
590822           -0.582347              -0.05133             -0.312371   
590823           -0.582347              -0.05133             -0.312371   
590825            0.119528              -0.05133             -0.312371   
590826           -0.582347              -0.05133             -0.312371   
590828           -0.582347              -0.05133             -0.294876   

        CR_PROD_CNT_VCU  REST_AVG_CUR  AMOUNT_RUB_NAS_PRC  \
ID                                                          
146841        -0.169589      0.477531           -0.248485   
146842        -0.169589     -0.330458           -0.248485   
146843        -0.169589      0.247411           -0.248485   
146844        -0.169589     -0.124857           -0.248485   
146845        -0.169589      0.029532           -0.248485   
...                 ...           ...                 ...   
590822        -0.169589     -0.301613           -0.248485   
590823        -0.169589      1.927086            2.804227   
590825        -0.169589      0.843853            0.113815   
590826        -0.169589     -0.288932            3.034981   
590828        -0.169589     -0.292957           -0.248485   

        TRANS_COUNT_SUP_PRC  ...  PACK_103  PACK_104  PACK_105  PACK_107  \
ID                           ...                                           
146841            -1.004598  ...         0         0         0         0   
146842             1.446347  ...         0         0         0         0   
146843            -1.004598  ...         0         0         0         0   
146844            -1.004598  ...         0         0         0         0   
146845            -1.004598  ...         0         0         0         0   
...                     ...  ...       ...       ...       ...       ...   
590822            -1.004598  ...         0         1         0         0   
590823            -1.004598  ...         0         1         0         0   
590825             0.135764  ...         0         0         0         0   
590826            -1.004598  ...         0         0         0         0   
590828            -1.004598  ...         0         0         0         0   

        PACK_108  PACK_109  PACK_301  PACK_k01  PACK_m01  PACK_o01  
ID                                                                  
146841         0         0         0         1         0         0  
146842         0         0         0         0         0         0  
146843         0         0         0         0         0         0  
146844

In [3]:
X = df.drop(columns = 'TARGET'); X

CR_PROD_CNT_IL  AMOUNT_RUB_CLO_PRC  TURNOVER_DYNAMIC_IL_1M  \
ID                                                                   
146841       -0.243932           -0.380232               -0.044824   
146842       -0.243932            0.016835               -0.044824   
146843       -0.243932           -0.313313               -0.044824   
146844       -0.243932           -0.380232               -0.044824   
146845       -0.243932           -0.380232               -0.044824   
...                ...                 ...                     ...   
590822       -0.243932           -0.380232               -0.044824   
590823       -0.243932           -0.380232               -0.044824   
590825       -0.243932            0.019401               -0.044824   
590826       -0.243932           -0.380232               -0.044824   
590828       -0.243932           -0.380232               -0.044824   

        AMOUNT_RUB_SUP_PRC  REST_DYNAMIC_FDEP_1M  REST_DYNAMIC_SAVE_3M  \
ID                                                                       
146841           -0.582347              -0.05133              2.356500   
146842            1.221828              -0.05133             -0.312371   
146843           -0.582347              -0.05133             -0.312371   
146844           -0.582347              -0.05133             -0.283428   
146845           -0.582347              -0.05133             -0.312371   
...                    ...                   ...                   ...   
590822           -0.582347              -0.05133             -0.312371   
590823           -0.582347              -0.05133             -0.312371   
590825            0.119528              -0.05133             -0.312371   
590826           -0.582347              -0.05133             -0.312371   
590828           -0.582347              -0.05133             -0.294876   

        CR_PROD_CNT_VCU  REST_AVG_CUR  AMOUNT_RUB_NAS_PRC  \
ID                                                          
146841        -0.169589      0.477531           -0.248485   
146842        -0.169589     -0.330458           -0.248485   
146843        -0.169589      0.247411           -0.248485   
146844        -0.169589     -0.124857           -0.248485   
146845        -0.169589      0.029532           -0.248485   
...                 ...           ...                 ...   
590822        -0.169589     -0.301613           -0.248485   
590823        -0.169589      1.927086            2.804227   
590825        -0.169589      0.843853            0.113815   
590826        -0.169589     -0.288932            3.034981   
590828        -0.169589     -0.292957           -0.248485   

        TRANS_COUNT_SUP_PRC  ...  PACK_103  PACK_104  PACK_105  PACK_107  \
ID                           ...                                           
146841            -1.004598  ...         0         0         0         0   
146842             1.446347  ...         0         0         0         0   
146843            -1.004598  ...         0         0         0         0   
146844            -1.004598  ...         0         0         0         0   
146845            -1.004598  ...         0         0         0         0   
...                     ...  ...       ...       ...       ...       ...   
590822            -1.004598  ...         0         1         0         0   
590823            -1.004598  ...         0         1         0         0   
590825             0.135764  ...         0         0         0         0   
590826            -1.004598  ...         0         0         0         0   
590828            -1.004598  ...         0         0         0         0   

        PACK_108  PACK_109  PACK_301  PACK_k01  PACK_m01  PACK_o01  
ID                                                                  
146841         0         0         0         1         0         0  
146842         0         0         0         0         0         0  
146843         0         0         0         0         0         0  
146844

In [4]:
y = df.TARGET

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.33,
                                                    random_state=8,
                                                   shuffle=True,
                                                   stratify=y)

In [6]:
from sklearn.ensemble import RandomForestClassifier

In [7]:
params = {'n_estimators':[200, 300, 400], 
          'max_depth': [10, 50, None],
         'max_samples': [20000, None]}

In [8]:
%%time
estimator = RandomForestClassifier(criterion='gini', 
                                   max_features='sqrt', 
                                   bootstrap=True, 
                                   oob_score=False, 
                                   n_jobs=-1,
                                   random_state=8, 
                                   class_weight='balanced_subsample')
forest_clf = GridSearchCV(estimator=estimator,
                          param_grid=params,
                          scoring='balanced_accuracy', 
                          n_jobs=-1,
                          refit=True,
                          cv=2).fit(X_train, y_train)

CPU times: total: 5min 8s
Wall time: 18min 42s


In [9]:
forest_clf.best_score_

0.7188585271804502

In [10]:
forest_clf.best_params_

{'max_depth': 10, 'max_samples': None, 'n_estimators': 400}

In [11]:
params = {'n_estimators':[350, 400, 500, 600], 
          'max_depth': [5, 10, 20],
         'max_samples': [None]}

In [12]:
%%time
estimator = RandomForestClassifier(criterion='gini', 
                                   max_features='sqrt', 
                                   bootstrap=True, 
                                   oob_score=False, 
                                   n_jobs=-1,
                                   random_state=8, 
                                   class_weight='balanced_subsample')
forest_clf = GridSearchCV(estimator=estimator,
                          param_grid=params,
                          scoring='balanced_accuracy', 
                          n_jobs=-1,
                          refit=True,
                          cv=2).fit(X_train, y_train)

CPU times: total: 7min 40s
Wall time: 18min 50s


In [13]:
forest_clf.best_score_

0.7195510868292379

In [14]:
forest_clf.best_params_

{'max_depth': 10, 'max_samples': None, 'n_estimators': 600}

In [15]:
best_forest_clf = forest_clf.best_estimator_

In [16]:
y_pred = best_forest_clf.predict(X_test)

In [17]:
metrics.accuracy_score(y_test, y_pred)

0.7212254613396125

In [18]:
metrics.balanced_accuracy_score(y_test, y_pred)

0.7211253501611661

In [19]:
metrics.recall_score(y_test, y_pred)

0.7210057621791514

In [20]:
y_pred_proba = best_forest_clf.predict_proba(X_test)

In [21]:
metrics.roc_auc_score(y_test, y_pred_proba[:, 1])

0.7958626992434866

In [22]:
metrics.confusion_matrix(y_test, y_pred)

array([[77655, 30013],
       [ 2663,  6882]], dtype=int64)

In [23]:
metrics.confusion_matrix(y_test, y_pred, normalize='true')

array([[0.72124494, 0.27875506],
       [0.27899424, 0.72100576]])

### _Additional features (client job positions) did not improve results so I will not use them in the following steps_

# Continue model selection without data on client job positions

## Gradient boosting

In [9]:
from sklearn.ensemble import HistGradientBoostingClassifier

In [10]:
params = {'learning_rate': [0.01, 0.1],
          'max_iter': [100, 200, 300],
          'max_leaf_nodes':[2, 5, 31], 
          'l2_regularization': [0.0, 0.1]}

In [12]:
%%time
estimator = HistGradientBoostingClassifier(loss='log_loss', 
                                           scoring='loss', 
                                           random_state=8)
boost_clf = GridSearchCV(estimator=estimator,
                          param_grid=params,
                          scoring='balanced_accuracy', 
                          n_jobs=-1,
                          refit=True,
                          cv=3).fit(X_train, y_train)

CPU times: total: 1min 51s
Wall time: 26min 42s


In [13]:
boost_clf.best_score_

0.5227319219783443

In [14]:
boost_clf.best_params_

{'l2_regularization': 0.1,
 'learning_rate': 0.1,
 'max_iter': 200,
 'max_leaf_nodes': 31}

In [36]:
boost_clf.best_score_

0.7236654347950653

In [37]:
boost_clf.best_params_

{'max_depth': 10, 'max_samples': None, 'n_estimators': 600}

In [15]:
best_boost_clf = boost_clf.best_estimator_

In [16]:
y_pred = best_boost_clf.predict(X_test)

In [17]:
metrics.accuracy_score(y_test, y_pred)

0.9190362843711875

In [18]:
metrics.balanced_accuracy_score(y_test, y_pred)

0.5228839574609124

In [19]:
metrics.recall_score(y_test, y_pred)

0.04965950759559979

In [20]:
y_pred_proba = best_boost_clf.predict_proba(X_test)

In [21]:
metrics.roc_auc_score(y_test, y_pred_proba[:, 1])

0.8476699023731898

In [22]:
metrics.confusion_matrix(y_test, y_pred)

array([[107249,    419],
       [  9071,    474]], dtype=int64)

In [23]:
metrics.confusion_matrix(y_test, y_pred, normalize='true')

array([[0.99610841, 0.00389159],
       [0.95034049, 0.04965951]])

### _Recall is much worse_

## Decision tree

In [10]:
from sklearn.tree import DecisionTreeClassifier

In [25]:
params = {'max_depth': [10, 50, 100, None],
         'max_features': ['sqrt', None]}

In [26]:
%%time
estimator = DecisionTreeClassifier(criterion='gini',
                                   random_state=8, 
                                   class_weight='balanced')
tree_clf = GridSearchCV(estimator=estimator,
                          param_grid=params,
                          scoring='balanced_accuracy', 
                          n_jobs=-1,
                          refit=True,
                          cv=3).fit(X_train, y_train)

CPU times: total: 11.3 s
Wall time: 1min 14s


In [27]:
tree_clf.best_score_

0.7297889758223342

In [29]:
tree_clf.best_params_

{'max_depth': 10, 'max_features': None}

In [33]:
params = {'max_depth': [5, 10, 15, 20, 30],
         'max_features': [None]}

In [34]:
%%time
estimator = DecisionTreeClassifier(criterion='gini',
                                   random_state=8, 
                                   class_weight='balanced')
tree_clf = GridSearchCV(estimator=estimator,
                          param_grid=params,
                          scoring='balanced_accuracy', 
                          n_jobs=-1,
                          refit=True,
                          cv=3).fit(X_train, y_train)

CPU times: total: 11.2 s
Wall time: 1min 3s


In [36]:
tree_clf.best_score_

0.7297889758223342

In [37]:
tree_clf.best_params_

{'max_depth': 10, 'max_features': None}

In [38]:
best_tree_clf = tree_clf.best_estimator_

In [39]:
y_pred = best_tree_clf.predict(X_test)

In [40]:
metrics.accuracy_score(y_test, y_pred)

0.7282553982919984

In [41]:
metrics.balanced_accuracy_score(y_test, y_pred)

0.7375074275726403

In [42]:
metrics.recall_score(y_test, y_pred)

0.748559455212153

In [44]:
y_pred_proba = best_tree_clf.predict_proba(X_test)

In [45]:
metrics.roc_auc_score(y_test, y_pred_proba[:, 1])

0.7953762797158126

In [46]:
metrics.confusion_matrix(y_test, y_pred)

array([[78216, 29452],
       [ 2400,  7145]], dtype=int64)

In [47]:
metrics.confusion_matrix(y_test, y_pred, normalize='true')

array([[0.7264554 , 0.2735446 ],
       [0.25144054, 0.74855946]])

### _Results are close to the results of the random forest classifier, even slightly better, with much faster training, which can be explained by a large size of the dataset which makes for small variance._

## Ada boost

In [8]:
from sklearn.ensemble import AdaBoostClassifier

In [74]:
params = {'n_estimators': [1, 5, 10, 20, 50],
         'learning_rate': [0.1, 0.5, 1, 5, 10],
         'base_estimator': [
             DecisionTreeClassifier(random_state=8, 
                                    class_weight='balanced',
                                    max_depth=1),
             DecisionTreeClassifier(random_state=8, 
                                    class_weight='balanced',
                                    max_depth=5),
             DecisionTreeClassifier(random_state=8, 
                                    class_weight='balanced',
                                    max_depth=10),
             DecisionTreeClassifier(random_state=8, 
                                    class_weight='balanced',
                                    max_depth=20)
         ]}

In [75]:
%%time
ada_clf = GridSearchCV(estimator=AdaBoostClassifier(random_state=8),
                       param_grid=params,
                       scoring='balanced_accuracy', 
                       n_jobs=-1,
                       refit=True,
                       cv=4).fit(X_train, y_train)

CPU times: total: 4min 40s
Wall time: 3h 7min 15s


In [76]:
ada_clf.best_score_

0.7547875784908085

In [77]:
ada_clf.best_params_

{'base_estimator': DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=8),
 'learning_rate': 0.1,
 'n_estimators': 50}

In [11]:
params = {'n_estimators': [30, 50, 70, 100],
         'learning_rate': [0.01, 0.05, 0.1],
         'base_estimator': [
             DecisionTreeClassifier(random_state=8, 
                                    class_weight='balanced',
                                    max_depth=3),
             DecisionTreeClassifier(random_state=8, 
                                    class_weight='balanced',
                                    max_depth=5),
             DecisionTreeClassifier(random_state=8, 
                                    class_weight='balanced',
                                    max_depth=7)
         ]}

In [12]:
%%time
ada_clf = GridSearchCV(estimator=AdaBoostClassifier(random_state=8),
                       param_grid=params,
                       scoring='balanced_accuracy', 
                       n_jobs=-1,
                       refit=True,
                       cv=3).fit(X_train, y_train)

CPU times: total: 5min 36s
Wall time: 2h 20min 28s


In [13]:
ada_clf.best_score_

0.7547461916924801

In [14]:
ada_clf.best_params_

{'base_estimator': DecisionTreeClassifier(class_weight='balanced', max_depth=3, random_state=8),
 'learning_rate': 0.1,
 'n_estimators': 100}

In [15]:
best_ada_clf = ada_clf.best_estimator_

In [16]:
y_pred = best_ada_clf.predict(X_test)

In [17]:
metrics.accuracy_score(y_test, y_pred)

0.7081040498920769

In [18]:
metrics.balanced_accuracy_score(y_test, y_pred)

0.758142099630603

In [19]:
metrics.recall_score(y_test, y_pred)

0.8179151388161341

In [21]:
y_pred_proba = best_ada_clf.predict_proba(X_test)

In [22]:
metrics.roc_auc_score(y_test, y_pred_proba[:, 1])

0.8304278588353197

In [23]:
metrics.confusion_matrix(y_test, y_pred)

array([[75192, 32476],
       [ 1738,  7807]], dtype=int64)

In [24]:
metrics.confusion_matrix(y_test, y_pred, normalize='true')

array([[0.69836906, 0.30163094],
       [0.18208486, 0.81791514]])

### _Imporoved recall and ROC_AUC_